codes/dappx/api/urls.py
from django.urls import path, include
from .views import UserLeadApi

urlpatterns = [
    path("lead/", UserLeadApi.as_view())
]

codes/dappx/urls.py
from django.conf.urls import url
from dappx import views

# SET THE NAMESPACE!
app_name = 'dappx'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

codes/dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from dappx import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from allauth.account.views import confirm_email as allauthemailconfirmation
schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('admin/', admin.site.urls),
    path('sa/', include('sa.urls')),
    path('configs/', include('configs.urls')),
    # path(r'^api/', include('api.urls')),
    # path(r'^dprojx/api/', include('dappx.api.urls')),
    # path(r'^rest-auth/', include('rest_auth.urls')),
    # path(r'^rest-auth/registration/account-confirm-email/(?P<key>[-:\w]+)/$',
    #    allauthemailconfirmation, name="account_confirm_email"),
    # path(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    # path(r'^$', views.index, name='index'),
    # path(r'^log-errors/', views.post_slack_errors, name='log-errors'),
    # url(r'^record/', views.record_video_screen, name='record'),
    # url(r'^video/', views.video, name='video'),
    # url(r'^video-monitor/', views.video_monitor, name='video-monitor'),
    # url(r'^upload/', views.upload, name='upload'),
    # url(r'^special/', views.special, name='special'),
    # url(r'^dappx/', include('dappx.urls')),
    # url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^user_login/$', views.user_login, name='user_login'),
    # path('create_notify_user/<str:user_hash>/', views.create_notify_user),
    # url(r'^monitor/$', views.monitor, name='monitor'),
    # url('^', include('django.contrib.auth.urls')),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codes/sa/urls.py
from django.urls import path

from . import views

# XXX rename to routes

urlpatterns = [
    path('api/start', views.start, name="start"),
    path('api/stop', views.stop, name="stop"),
    path('api/session_point', views.session_point,
         name="session_point"),
    path('api/get_distances', views.get_distances,
         name="get_distances"),
    path('api/stats', views.get_session_stats, name="get_session_stats"),
]

codes/dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput()
    )
    username = forms.CharField(widget=forms.HiddenInput(),
                               required=False)
    email = forms.CharField()

    class Meta():
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        notify_email = forms.EmailField(label='Notify Email')
        fields = ('name', 'notify_email', 'days_sober')

codes/dappx/api/views.py
from rest_framework import (viewsets, filters, status, mixins, generics)
from ..models import UserLead
from .serializers import UserLeadSerializer


class UserLeadApi(generics.CreateAPIView):
    queryset = UserLead.objects.all()
    serializer_class = UserLeadSerializer

codes/dappx/views.py
import datetime
import hashlib
import json
import logging
import mimetypes
import os
import requests
import uuid

from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.http import JsonResponse
from django.http.response import StreamingHttpResponse
# from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response
from rest_framework.status import HTTP_400_BAD_REQUEST, HTTP_200_OK
from wsgiref.util import FileWrapper

from . import email_utils
from . import notify_utils
from . import video_utils
from . import constants
from .models import UserProfileInfo
from .models import VideoUpload
from .models import UserMonitor
from dappx.forms import UserForm, UserProfileInfoForm
from utils import superuser_only
from utils import custom_render as render
from common import config

logger = config.get_logger()


def register(request):
    return render(request, 'dappx/index.html')


@superuser_only
def video(request):
    path = '/media/%s/%s' % (request.GET.get("user"),
                             request.GET.get("id"))
    return stream_video(request, path)


@login_required
def video_monitor(request):
    logger.error("View video request from: %s" % request.user)
    path = '/media/%s/%s' % (request.GET.get("user"), request.GET.get("id"))
    video = VideoUpload.objects.filter(videoUrl=path).first()

    if not video:
        raise Http404

    if video and request.user.is_superuser:
        return stream_video(request, path)

    video_owner = UserProfileInfo.objects.filter(user=video.user).first()

    # get monitors of user
    user_monitors = UserMonitor.objects.filter(user=video.user).all()
    user_monitor_emails = [u.notify_email for u in user_monitors]
    logging.info("User %s monitors are %s"
                 % (video.user.email, user_monitor_emails))

    monitor_user = UserProfileInfo.objects.filter(
        user__email=video_owner.notify_email
    ).first()

    if monitor_user:
        logger.info("monitor user for video is: %s" % monitor_user)
    else:
        logger.info("no monitor user")

    if monitor_user and monitor_user.user.email != request.user.email:
        raise Http404

    return stream_video(request, path)


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def monitor(request):
    return render(request, 'dappx/monitor.html', {})


def record_video_screen(request):
    return render(request, 'dappx/record.html')


def days_sober(date_joined):
    date_joined = (str(date_joined).split(" "))[0].split("-")
    current = datetime.datetime.now()
    joined = datetime.datetime(int(date_joined[0]),
                               int(date_joined[1]),
                               int(date_joined[2]))
    return (current - joined).days


@csrf_exempt
def post_slack_errors(request):
    url = 'https://hooks.slack.com/services/'
    url += 'TF6H12JQY/BF6H2L0M6/RMuFLttV91aKvlUXydV2yJgv'
    data = (str(request.POST))
    data += '\nSite: %s' % request.META['HTTP_HOST']
    body = {"text": "%s" % data,
            'username': 'js-logger'}

    requests.put(url, data=json.dumps(body))

    return JsonResponse({'error': 'Some error'}, status=200)


def convert_file(uploaded_file_url):
    outfile = "%s.mp4" % uploaded_file_url.rsplit(".", 1)[0]
    command = (
        'avconv -i ./%s -codec copy ./%s' % (uploaded_file_url, outfile)
    )
    print(command)
    os.system(command)
    return outfile


def compress_file(uploaded_file_url):
    outfile = "%s_resized.mp4" % uploaded_file_url.rsplit(".", 1)[0]
    command = (
        'avconv -i ./%s -strict -2 ./%s' % (uploaded_file_url, outfile)
    )
    print(command)
    os.system(command)
    return outfile


def stream_video(request, path):
    path = settings.BASE_DIR + path
    range_header = request.META.get('HTTP_RANGE', '').strip()
    range_match = video_utils.range_re.match(range_header)
    size = os.path.getsize(path)
    content_type, encoding = mimetypes.guess_type(path)
    content_type = content_type or 'application/octet-stream'
    if range_match:
        first_byte, last_byte = range_match.groups()
        first_byte = int(first_byte) if first_byte else 0
        last_byte = int(last_byte) if last_byte else size - 1
        if last_byte >= size:
            last_byte = size - 1
        length = last_byte - first_byte + 1
        resp = StreamingHttpResponse(video_utils.RangeFileWrapper(
            open(path, 'rb'), offset=first_byte, length=length), status=206,
            content_type=content_type
        )
        resp['Content-Length'] = str(length)
        resp['Content-Range'] = 'bytes %s-%s/%s' % (first_byte, last_byte,
                                                    size)
    else:
        resp = StreamingHttpResponse(
            FileWrapper(open(path, 'rb')), content_type=content_type)
        resp['Content-Length'] = str(size)
    resp['Accept-Ranges'] = 'bytes'
    return resp


def convert_and_save_video(myfile, request):
    user = request.user
    fs = FileSystemStorage()
    user_hash = hashlib.sha1(
        user.email.encode('utf-8')
    ).hexdigest()

    uploaded_name = (
        "%s/%s-%s" % (user_hash, uuid.uuid4(), myfile.name)
    ).lower()

    filename = fs.save(uploaded_name, myfile)
    uploaded_file_url = fs.url(filename)

    if uploaded_name[-4:] == '.mov':
        # ffmpeg!
        uploaded_file_url = convert_file(uploaded_file_url)
    # XXX resize video for android need to implement async processing

    logger.info("Uploaded video file: %s" % uploaded_file_url)

    # now lets create the db entry
    user = User.objects.get(id=user.id)
    video = VideoUpload.objects.create(
        videoUrl=uploaded_file_url, user=user,
        source=request.data.get("source")
    )

    notify_utils.notify_monitors_video(request, {
        "event_type": "video",
        "video_model": video,
        "uploaded_file_url": uploaded_file_url,
        "video_link": video.video_monitor_link()})

    return video


def upload_org_logo(myfile, request):
    fs = FileSystemStorage()
    uid = uuid.uuid4()
    uploaded_name = (
        "%s/%s-%s" % ('img', uid, myfile.name)
    ).lower()

    filename = fs.save(uploaded_name, myfile)

    save_filename = (
        "%s-%s" % (uid, myfile.name)
    ).lower()

    return save_filename


@csrf_exempt
@login_required
def upload(request):
    if request.method == 'POST' and request.FILES['file']:
        logger.info("Video upload: %s" % request.POST)

        myfile = request.FILES['file']
        convert_and_save_video(myfile, request)

        return JsonResponse({'error': 'Some error'}, status=200)


# @csrf_exempt
@login_required
def record_video(request):
    files = request.data.get("file")
    userId = request.data.get('userId')
    fs = FileSystemStorage()
    try:
        filename = fs.save(files.name, files)
        uploaded_file_url = fs.url(filename)
    except Exception:
        logger.exception("Error")
        return Response({'error': 'Error uploading file'},
                        status=HTTP_400_BAD_REQUEST)
    print(type(files))
    print(uploaded_file_url)

    user = User.objects.get(id=userId)
    try:
        VideoUpload.objects.create(videoUrl=uploaded_file_url,
                                   user=user)
    except Exception:
        logger.exception("Error")
        return Response({'error': 'Error uploading file'},
                        status=HTTP_400_BAD_REQUEST)

    return Response({
        'message', 'Success'
    }, status=HTTP_200_OK)


def _create_user(**data):
    data['email'] = data['email'].lower()
    data['username'] = data['email']
    print("######Get####",data.get("notify_email", ""))
    request = data.get('request')
    monitor_user = None
    if data.get('notify_email'):
        monitor_user = User.objects.filter(
            username=data.get('notify_email').lower()
        ).first()

    user_form = UserForm(data)
    profile_data = {}
    profile_data['name'] = data['name']
    profile_data['notify_email'] = data['email']
    profile_data['days_sober'] = '0'
    profile_form = UserProfileInfoForm(profile_data)
    print("user form ", user_form)
    if user_form.is_valid() and profile_form.is_valid():
        print("Enter in this form")
        user = user_form.save()
        print("UERERERE %s" % user)
        user.set_password(user.password)
        user.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.phone = data.get("phone", "")
        profile.days_sober = data.get("days_sober", 0)
        profile.sober_date = data.get("sober_date", 0)
        profile.name = data.get("name", "")
        profile.notify_email = data.get("notify_email", "")
        profile.source = data.get("source", "")
        profile.save()

        # log user in!
        username = data.get('email')
        password = data.get('password')
        user = authenticate(username=username, password=password)

        if monitor_user:
            logger.info("I HAVE MONITOR USER")
            email_utils.send_raw_email(
                to_email=data.get("notify_email"),
                reply_to=data.get('email'),
                subject='useIAM: %s added you as a monitor'
                        % data.get('name'),
                message_text=constants.existing_monitor_message)
        elif data.get('notify_email'):
            url = "https://" + request.META['HTTP_HOST']

codes/templates/dappx/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />
    <!--CSS -->
    <link rel="stylesheet" href="/static/style.css?v=1.1">
    <script src="/static/custom.js?v=1.1"></script>
    <script src="/static/jquery-3.3.1.js"></script>
    <script src="/static/sweetalert.min.js"></script>
    <title>IAM</title>
</head>
<body>
    <div id='overlay_loading'></div>
    <header>
        <div class="mainContainer">
          {% if user.is_authenticated %}
            <nav class="toggleBar">
                <span class="bar bar1"></span>
                <span class="bar bar2"></span>
                <span class="bar bar3"></span>
            </nav>
          {% endif %}
          <div class="logo">
            <img src="/static/eye.png" alt="logo" width='100px'>
          </div>
        </div>
    </header>
      <!--
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}
    -->
    {% block video_block %}
    {% endblock %}
    {% block body_block %}
    {% endblock %}
    {% block gps_block %}
    {% endblock %}

   {% if user.is_authenticated %}
    <div class="slideMenu">
        <h4 class="textCenter">Days Sober: {{sober_days}}</h4>
        <h4 class="textCenter">Your Email: {{ request.user.email }}</h4>
        <h4 class="textCenter">Notify Email: {{ notify_email }}</h4>
        <h4 class="textCenter"><a href="/logout">Logout</a></h4>
    </div>
   {% endif %}

  </body>
</html>

codes/templates/dappx/create_notify_user.html
{% extends 'dappx/base.html' %}
{% block body_block %}
<div class="mainContainer" style='margin-top:25px'>
    <div class="modal-content" style="padding: 20px; background: none no-repeat scroll 0 0 #fff; position: relative;">
      <h1>Set Account Password</h1>
      <form method="post" action=".">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <p>
          <input type="text" name="email" value="{{ username }}" disabled placeholder="Email">
          </p>
          <p>
          <input type="password" name="password" placeholder="Password">
          </p>
          <input type="submit" name="" class="btnSubmit" value="Login">
      </form>
    </div>
</div>
{% endblock %}

codes/templates/dappx/gps-event.html
{% extends "dappx/base.html" %}
{% block gps_block %}
		<form id="upload_vid_form" method="post" style="display: inline;" enctype="multipart/form-data">
      <input type='hidden' name='lat'>
      <input type='hidden' name='long'>
    <div class="mainContainer">
        <div class="eventBox">
						<label>Enter a note</label>
						<textarea placeholder="Add Description of Event" name='msg'></textarea>
        </div>
    </div>

    <div class="secAction">
        <div class="mainContainer">
				  <button class="actionBtn is-visible" id="locationAuth">Submit Checkin</button>
        </div>
    </div>

		</form>


    <div class="modal" id="LocationModal">
        <div class="modal-overlay"></div>
        <div class="modal-wrapper modal-transition">
            <div class="modal-header">
            </div>
            <div class="modal-body">
                <div class="modal-content">
                    <div class="textCenter">
                        <img src="/static/location.png">
                        <h3 class="locAuthTitle">Location Permission</h3>
                        <p class="locAuthDesc">
									Please allow permissions for accessing your location through GPS.<br><br>
									Press allow when ready.
								</p>
                        <button class="btnSubmit">Allow</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

codes/templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}

	{% if user.is_authenticated %}
		<div class="mainContainer">
        <ol class="chat">
            <li class="other">
                <div class="avatar"><img src="static/pam2.png" draggable="false"></div>
                <div class="msg">
						  <p>Hi {{name}}, What would you like to do?</p>
                </div>
            </li>
        </ol>
    </div>

	<div class="secAction">
        <div class="mainContainer">
				<form id='upload_vid_form' method='post' style='display: inline;'
						enctype="multipart/form-data">
					<input type="file" accept="video/*" id='upload-vid'
					       capture="environment" style='display:none;'>
					<button class="actionBtn btnVideo">Take a Video</button>
				</form>
            <button class="actionBtn btnEvent">Attend Event<br><span>(Check-In/Check-Out)</span></button>
        </div>
    </div>


    <div class="modal" id="takeavideoModal">
        <div class="modal-overlay"></div>
        <div class="modal-wrapper modal-transition">
            <div class="modal-header">
                <h2 class="modal-heading">Take a Video</h2>
            </div>
            <div class="modal-body">
                <div class="modal-content">
            	    <h2>1) Ensure you are connected to Wifi</h2>
							    <h2>2) When you click record:</h2>
							    <h2>3) Show the your medicine prescription bottle to the camera</h2>
							    <h2>4) Take your pill.</h2>
							    <h2>5) Submit Short video.</h2>
                  <div style='text-align:center'>
						      <button class="actionBtn btnVideo" id="takevideobtn">Take a video</button>
                  </div>
                </div>
            </div>
        </div>
    </div>


    {% else %}
	 <input type="hidden" id="user_taken" name="variable" value="{{ user_taken }}">
    <div class="mainContainer">
        <ol class="chat">
            <li class="other">
                <div class="avatar"><img src="static/pam2.png" draggable="false"/></div>
                <div class="msg">
                    <p>Meet IAM, your Interactive Accountability Manager.</p>
                </div>
            </li>
            <li class="other">
                <div class="avatar"><img src="static/pam2.png" draggable="false"/></div>
                <div class="msg">
                    <p>Are you new or would you like to sign in?</p>
                </div>
            </li>
        </ol>
    </div>
    <div class="secAction">
        <div class="mainContainer">
            <button class="actionBtn" id="signin">Sign in</button>
            <button class="actionBtn" id="signup">I am new</button>
        </div>
    </div>
    <div class="modal" id="signinModal">
        <div class="modal-overlay"></div>
        <div class="modal-wrapper modal-transition">
            <div class="modal-header">
                <!-- <img src="static/modalLogo.png" alt="Modal Logo" class="modalLogo"> -->
                <h2 class="modal-heading">Hello, Please login</h2>
            </div>
            <div class="modal-body">
                <div class="modal-content">
                    <form class="popupForm" action="/user_login/" enctype=multipart/form-data method="POST">
							   {% csrf_token %}
								<p>
									<label>Email:</label>
									{{ user_form.email}}
								</p>
								<p>
									<label>Password:</label>
							      {{ user_form.password}}
								</p>
								<p>
									<label>Notify Email</label>
									{{ profile_form.notify_email }}
								</p>
                        <p class="textCenter"><a href="/password_reset">Forgot password?</a></p>
                        <input type="submit" value="Login" class="btnSubmit">
                    </form>
                    <p class="textCenter signupNeed">Don’t have an account? <a href="#">Sign Up</a></p>
                </div>
            </div>
        </div>
    </div>


    <div class="modal" id="signupModal">
        <div class="modal-overlay"></div>
        <div class="modal-wrapper modal-transition">
            <div class="modal-header">
                <!--<img src="static/modalLogo.png" alt="Modal Logo" class="modalLogo">-->
                <h2 class="modal-heading">Create an account</h2>
            </div>
            <div class="modal-body">
                <div class="modal-content">
                    <form class="popupForm" enctype=multipart/form-data method="POST">
							  {% csrf_token %}
							  {{ user_form.as_p }}
							  {{ profile_form.as_p }}
                        <input type="submit" value="Sign Up" class="btnSubmit">
								<!--
                        <input type="text" placeholder="Full Name">
                        <input type="Email" placeholder="Email">
                        <input type="tel" placeholder="Phone">
                        <input type="password" placeholder="Password">
                        <input type="password" placeholder="Confirm Password">
								-->
                    </form>
                </div>
            </div>
        </div>
    </div>
	{% endif %}
{% endblock %}

codes/templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
<div class="mainContainer" style='margin-top:25px'>
    <div class="modal-content" style="padding: 20px; background: none no-repeat scroll 0 0 #fff; position: relative;">
      <h1>Login here</h1>
      <form method="post" action="{% url 'dappx:user_login' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <p>
          <input type="text" name="email" placeholder="Email">
          </p>
          <p>
          <input type="password" name="password" placeholder="Password">
          </p>
          <input type="submit" name="" class="btnSubmit" value="Login">
      </form>
    </div>
</div>
{% endblock %}

codes/templates/dappx/monitor.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="mainContainer">
  <ol class="chat">
      <li class="other">
          <div class="avatar"><img src="/static/pam2.png" draggable="false"></div>
          <div class="msg" style='text-align:center'>
				<div>You will now beable to view video submissions sent to
					  {{ request.user.email }} after logging in</div>
            <!--{% for user in users %}
            <div>
              {{ user.name }} - {{ user.user.email }}
              <br />
            </div>
            {% endfor %}
				-->
          </div>
      </li>
  </ol>
</div>
{% endblock %}

codes/templates/dappx/record.html
{% extends "dappx/base.html" %}
{% block video_block %}
    <div class="mainContainer">
        <video id="myVideo" width="100%" height="340" controls="false">
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="secAction">
        <div class="mainContainer">
            <button class="actionBtn singleBtn">Start Recording</button>
        </div>
    </div>
	<button id='btn-upload' style='display:none'>upload</button>
	<button id='start' style='display:none'>start</button>
	<button id='stop' style='display:none'>stop</button>
    <script src="/static/custom_record.js"></script>
{% endblock %}

codes/templates/dappx/registration.html
{% extends "dappx/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}

codes/templates/dappx/video.html
<!doctype html>
<html lang="en">
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />
      <!--CSS -->
      <script src="/static/jquery-3.3.1.js"></script>
  </head>
  <body>
    <video width='320' height='240' controls>
      <source src='https://app.usepam.com/media/{{user}}/{{id}}'
       type="video/mp4">
      error unable to play video
    </video>
  </body>
</html>